USE [master]
GO

/****** Object:  Database [Unemployment]    Script Date: 7/12/2017 10:22:59 ******/
CREATE DATABASE [Unemployment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Unemployment', FILENAME = N'/var/opt/mssql/data/Unemployment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Unemployment_log', FILENAME = N'/var/opt/mssql/data/Unemployment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Unemployment] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Unemployment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Unemployment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Unemployment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Unemployment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Unemployment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Unemployment] SET ARITHABORT OFF 
GO

ALTER DATABASE [Unemployment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Unemployment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Unemployment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Unemployment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Unemployment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Unemployment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Unemployment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Unemployment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Unemployment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Unemployment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Unemployment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Unemployment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Unemployment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Unemployment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Unemployment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Unemployment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Unemployment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Unemployment] SET RECOVERY FULL 
GO

ALTER DATABASE [Unemployment] SET  MULTI_USER 
GO

ALTER DATABASE [Unemployment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Unemployment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Unemployment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Unemployment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Unemployment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Unemployment] SET QUERY_STORE = OFF
GO

USE [Unemployment]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Unemployment] SET  READ_WRITE 
GO


