FROM microsoft/mssql-server-linux:latest
LABEL name "adventureworks16"
LABEL author "Maarten Merken"
ENV "ACCEPT_EULA" "Y"
ENV "SA_PASSWORD" "abc123$%"

COPY AdventureWorks2016.bak /var/opt/mssql/backup/